name := "Connected Components"
version := "1.0"
scalaVersion := "2.12.15"
libraryDependencies += "org.apache.spark" %% "spark-core" % "3.2.0"
libraryDependencies += "org.apache.spark" %% "spark-graphx" %"3.2.0"
libraryDependencies += "org.apache.spark" %% "spark-sql" %"3.2.0"
